name: Pipeline IaC

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - et-final

permissions:
  contents: read

jobs:
  calidad-seguridad:
    name: Calidad y seguridad IaC
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Verificar formato
        run: terraform fmt -check -recursive Infra

      - name: Inicializar Terraform
        run: terraform -chdir=Infra init -backend=false

      - name: Validar Terraform
        run: terraform -chdir=Infra validate

      - name: Instalar TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Ejecutar TFLint
        run: tflint --chdir=Infra

      - name: Instalar Checkov
        run: pip install checkov

      - name: Ejecutar Checkov
        run: checkov -d Infra --skip-check CKV_TF_1

      - name: Generar plan de Terraform
        run: |
          terraform -chdir=Infra plan \
            -input=false \
            -lock=false \
            -refresh=false \
            -out=tfplan \
            -var="ci_mode=true"

      - name: Convertir plan a JSON
        run: terraform -chdir=Infra show -json tfplan > Infra/tfplan.json

      - name: Instalar OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa

      - name: Evaluar políticas OPA
        run: |
          EC2_DENIES=$(./opa eval \
            --format raw \
            --data policies \
            --input Infra/tfplan.json \
            "count(data.policies.ec2.deny)")

          SG_DENIES=$(./opa eval \
            --format raw \
            --data policies \
            --input Infra/tfplan.json \
            "count(data.policies.sg.deny)")

          echo "Incumplimientos EC2: $EC2_DENIES"
          echo "Incumplimientos Security Group: $SG_DENIES"

          if [ "$EC2_DENIES" -gt 0 ] || [ "$SG_DENIES" -gt 0 ]; then
            echo "Se detectaron configuraciones que incumplen las políticas."

            ./opa eval \
              --format pretty \
              --data policies \
              --input Infra/tfplan.json \
              "data.policies"

            exit 1
          fi

          echo "Todas las políticas de seguridad fueron aprobadas."